config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/:provider/callback' => 'sessions#create'

  get '/signout' => 'sessions#destroy', as: :signout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end

  # the following code pulls user avatars from FB:

  def largeimage
    "http://graph.facebook.com/#{self.uid}/picture?type=large"
  end
  
  def normalimage
    "http://graph.facebook.com/#{self.uid}/picture?type=normal"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
 
  private
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], 
    auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div id="user-widget">
	<% if current_user %>
		Welcome, <strong><%= current_user.name %></strong>!<br />
		<% if current_user.provider == "facebook" %>
			<%= image_tag current_user.normalimage %><br />
		<% else %>
			<%= image_tag current_user.image %><br />
		<% end %>
		<%= link_to "Sign Out", signout_path, id: "sign_out" %>
	<% else %>
		<%= link_to "/auth/facebook", id: "sign_in" do %>
			<p><i class="fa fa-facebook fa-2x"></i> Sign In with Facebook</p>
		<% end %>
		<%= link_to "/auth/github" do %>
			<p><i class="fa fa-github fa-2x"></i> Sign In with GitHub</p>
		<% end %>
	<% end %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmniauthExamples</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
	    <%= yield %>
  	</div>
  </body>
</html>